modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/YiRanMushroom/GTMQoL"

[[mods]]
modId = "gtmqol"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
authors = "${mod_author}"
description = '''
Runtime resource and data generation utilities for GTCEu.
'''

[[dependencies.gtmqol]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtmqol]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtmqol]]
modId = "gtceu"
mandatory = true
versionRange = "[${gtceu_version},)"
ordering = "AFTER"
side = "BOTH"
