GTCEuStartupEvents.registry("gtceu:machine", event => {
    // const MoniRecipeTypesExtension = Java.loadClass("com.yiran.minecraft.gtmqol.integration.monifactory.MoniRecipeTypesExtension");

    event.create("omni_prismatic_crucible", "multiblock")
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes("gtceu:omni_prismatic_recipe")
        // .recipeTypes(MoniRecipeTypesExtension.OMNI_PRISMATIC_CRUCIBLE_RECIPE)
        .recipeModifiers(GTRecipeModifiers.OC_NON_PERFECT)
        .appearanceBlock(MoniBlocks.DIMENSIONAL_STABILIZATION_NETHERITE_CASING)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("LLL#######LLL", "#############", "#############", "#############", "#############", "#############", "#############", "#############", "#############", "#############")
            .aisle("LLLLL###LLLLL", "#F#########F#", "#F#########F#", "#F#########F#", "#F#########F#", "#F#########F#", "#F#########F#", "#F#########F#", "#F#l#####l#F#", "#lll#####lll#")
            .aisle("LLLLLLLLLLLLL", "##F#######F##", "##F#######F##", "##F#######F##", "##F#######F##", "##F#######F##", "##F#######F##", "##F#######F##", "##Fll###llF##", "#llll###llll#")
            .aisle("#LLCCCCCCCLL#", "###C#####C###", "###C#####C###", "###C#####C###", "###C#####C###", "###C#####C###", "###C#####C###", "###C#####C###", "#llCCC#CCCll#", "#llll###llll#")
            .aisle("#LLCLLCLLCLL#", "#####LCL#####", "######C######", "#############", "#############", "#############", "#############", "#####lCl#####", "##lClCCClCl##", "##ll#####ll##")
            .aisle("##LCLLLLLCL##", "####L###L####", "#############", "#############", "#############", "#############", "######F######", "####llCll####", "###CCl#lCC###", "#############")
            .aisle("##LCCLLLCCL##", "####C###C####", "####C###C####", "#############", "#############", "#############", "#####FPF#####", "####CCCCC####", "####C###C####", "#############")
            .aisle("##LCLLLLLCL##", "####L###L####", "#############", "#############", "#############", "#############", "######F######", "####llCll####", "###CCl#lCC###", "#############")
            .aisle("#LLCLLCLLCLL#", "#####LCL#####", "######C######", "#############", "#############", "#############", "#############", "#####lCl#####", "##lClCCClCl##", "##ll#####ll##")
            .aisle("#LLCCCCCCCLL#", "###C#####C###", "###C#####C###", "###C#####C###", "###C#####C###", "###C#####C###", "###C#####C###", "###C#####C###", "#llCCC#CCCll#", "#llll###llll#")
            .aisle("LLLLLLMLLLLLL", "##F#######F##", "##F#######F##", "##F#######F##", "##F#######F##", "##F#######F##", "##F#######F##", "##F#######F##", "##Fll###llF##", "#llll###llll#")
            .aisle("LLLLL###LLLLL", "#F#########F#", "#F#########F#", "#F#########F#", "#F#########F#", "#F#########F#", "#F#########F#", "#F#########F#", "#F#l#####l#F#", "#lll#####lll#")
            .aisle("LLL#######LLL", "#############", "#############", "#############", "#############", "#############", "#############", "#############", "#############", "#############")
            .where("L",
                Predicates.blocks(MoniBlocks.DIMENSIONAL_STABILIZATION_NETHERITE_CASING.get())
                    .setMinGlobalLimited(88)
                    .or(Predicates.autoAbilities(definition.getRecipeTypes())))
            .where("l", Predicates.blocks(MoniBlocks.DIMENSIONAL_STABILIZATION_NETHERITE_CASING.get()))
            .where("C", Predicates.blocks(MoniBlocks.PRISM_GLASS.get()))
            .where("M", Predicates.controller(Predicates.blocks(definition.getBlock())))
            .where("P", Predicates.blocks(MoniBlocks.PRISMATIC_FOCUS.get()))
            .where("F", Predicates.frames(GTMaterials.Neutronium))
            .where("#", Predicates.any())
            .build())
        .workableCasingModel(MoniLabs.id("block/casing/netherite"), GTCEu.id("block/multiblock/processing_array"))
});