ServerEvents.recipes(event => {
    event.recipes.gtceu["pcb_factory"]("wetware_circuit_board_sulfuric_acid")
        .itemInputs("8x #forge:plates/reinforced_epoxy_resin")
        .itemInputs("64x #forge:foils/annealed_copper")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemInputs("32x #forge:foils/palladium")
        .inputFluids("gtceu:sulfuric_acid 2000")
        .itemInputs("4x #forge:foils/niobium_titanium")
        .inputFluids("gtceu:sterilized_growth_medium 1000")
        .itemOutputs("16x gtceu:wetware_printed_circuit_board")
        .duration(25 * 20 * 4)
        .EUt(30)

    event.recipes.gtceu["pcb_factory"]("wetware_circuit_board_hexafluorosilicic_acid")
        .itemInputs("8x #forge:plates/reinforced_epoxy_resin")
        .itemInputs("64x #forge:foils/annealed_copper")
        .inputFluids("gtceu:hexafluorosilicic_acid 120")
        .itemInputs("32x #forge:foils/palladium")
        .inputFluids("gtceu:hexafluorosilicic_acid 240")
        .itemInputs("4x #forge:foils/niobium_titanium")
        .inputFluids("gtceu:sterilized_growth_medium 1000")
        .itemOutputs("16x gtceu:wetware_printed_circuit_board")
        .duration(25 * 20 * 4)
        .EUt(30)

    event.recipes.gtceu["pcb_factory"]("carbon_mesh_reinforced_printed_circuit_board_oxalic_acid")
        .itemInputs("8x gtceu:carbon_fiber_mesh")
        .inputFluids("gtceu:polyether_ether_ketone 576")
        .itemInputs("40x #forge:foils/osmium")
        .inputFluids("gtceu:oxalic_acid_solution 5000")
        .itemInputs("24x #forge:foils/lumium")
        .itemInputs("64x #forge:bolts/duranium")
        .inputFluids("gtceu:dielectric_mirror_solution 2304")
        .itemOutputs("16x kubejs:optical_processing_unit")
        .duration(25 * 20 * 4)
        .EUt(30)

    event.recipes.gtceu["pcb_factory"]("carbon_mesh_reinforced_printed_circuit_board_iron_iii")
        .itemInputs("8x gtceu:carbon_fiber_mesh")
        .inputFluids("gtceu:polyether_ether_ketone 576")
        .itemInputs("40x #forge:foils/osmium")
        .inputFluids("gtceu:iron_iii_chloride 10000")
        .itemInputs("24x #forge:foils/lumium")
        .itemInputs("64x #forge:bolts/duranium")
        .inputFluids("gtceu:dielectric_mirror_solution 2304")
        .itemOutputs("16x kubejs:optical_processing_unit")
        .duration(25 * 20 * 4)
        .EUt(30)

    event.recipes.gtceu["pcb_factory"]("carbon_mesh_reinforced_printed_circuit_board_sodium_persulfate")
        .itemInputs("8x gtceu:carbon_fiber_mesh")
        .inputFluids("gtceu:polyether_ether_ketone 576")
        .itemInputs("40x #forge:foils/osmium")
        .inputFluids("gtceu:sodium_persulfate 20000")
        .itemInputs("24x #forge:foils/lumium")
        .itemInputs("64x #forge:bolts/duranium")
        .inputFluids("gtceu:dielectric_mirror_solution 2304")
        .itemOutputs("16x kubejs:optical_processing_unit")
        .duration(25 * 20 * 4)
        .EUt(30)

    event.recipes.gtceu["pcb_factory"]("null_infused_circuit_board")
        .itemInputs("8x gtceu:carbon_fiber_mesh")
        .inputFluids("gtceu:polyether_ether_ketone 576")
        .inputFluids("gtceu:living_soldering_alloy 144")
        .itemInputs("2x #forge:foils/meta_null")
        .itemInputs("2x gtceu:nano_cpu_chip")
        .itemInputs("32x #forge:fine_wires/necrosiderite")
        .itemInputs("64x #forge:foils/naquadah_alloy")
        .inputFluids("gtceu:iron_iii_chloride 20000")
        .itemOutputs("16x kubejs:null_infused_printed_circuit_board")
        .duration(5 * 4 * 20)
        .EUt(30)

    event.recipes.gtceu["pcb_factory"]("neuro_circuit_board_sulfuric_acid")
        .itemInputs("8x #forge:plates/reinforced_epoxy_resin")
        .itemInputs("16x #forge:plates/annealed_copper")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemInputs("8x #forge:plates/palladium")
        .inputFluids("gtceu:sulfuric_acid 2000")
        .itemInputs("#forge:plates/niobium_titanium")
        .itemInputs("16x gtceu:stem_cells")
        .itemInputs("16x #forge:plates/enderium")
        .inputFluids("gtceu:sterilized_growth_medium 1500")
        .itemOutputs("16x gtceu:neuro_processing_unit")
        .duration(25 * 20 * 4)
        .EUt(30)

    event.recipes.gtceu["pcb_factory"]("neuro_circuit_board_hexafluorosilicic_acid")
        .itemInputs("8x #forge:plates/reinforced_epoxy_resin")
        .itemInputs("16x #forge:plates/annealed_copper")
        .inputFluids("gtceu:hexafluorosilicic_acid 120")
        .itemInputs("8x #forge:plates/palladium")
        .inputFluids("gtceu:hexafluorosilicic_acid 240")
        .itemInputs("#forge:plates/niobium_titanium")
        .itemInputs("16x gtceu:stem_cells")
        .itemInputs("16x #forge:plates/enderium")
        .inputFluids("gtceu:sterilized_growth_medium 1500")
        .itemOutputs("16x gtceu:neuro_processing_unit")
        .duration(25 * 20 * 4)
        .EUt(30)
})